name: Build and Test

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Build the app
        run: npm install
      - name: Run integration tests
        run: npm test

  deploy:
    needs: build
    # if: github.event_name == 'worckflow_dispatch'
    steps:
      - name: Render.com Deploy
        uses: ttskch/render-deploy@v1.0.0
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
